steps:
  - name: check
    image: rust
    commands:
      - cargo check
      - cargo test

  - name: build
    image: rust
    commands:
      - cargo build --release

  - name: prepare for release
    image: rust
    commands:
      - cp target/release/skibidilang skibidilang-x86_64

  - name: release
    image: woodpeckerci/plugin-release
    settings:
      files:
        # Could also be "hello-world*" to match both
        - 'skibidilang-x86_64'
      prerelease: true
      title: 'Nightly build'
      api_key:
        from_secret: ACCESS_TOKEN
