name: Build compiler 
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build:
    runs-on: docker
    container:
      image: rust:alpine
    steps:
      - name: Install node for checkout
        run: |
          apk add --no-cache nodejs npm git musl-dev
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check code 
        run: |
          cargo check
          cargo test
      - name: Build code 
        run: |
          cargo build --release 
      - name: Rename files
        run: |
          mv ./target/release/skibidilang ./skibidilang-arm64
      - name: Publish release  
        uses: https://gitea.com/akkuman/gitea-release-action@v1
        with:
          files: |-
            skibidilang-arm64
          name: 'ci build'
          tag_name: 'cibuild'
          token: '${{secrets.RELEASE_TOKEN}}'
          api_key: '${{secrets.RELEASE_TOKEN}}'

      - run: echo "🍏 This job's status is ${{ job.status }}."
